.TH hist2workspace 1 
.SH SYNOPSIS
usage: hist2workspace [-h] [-standard_form STANDARD_FORM]
                      [-number_counting_form NUMBER_COUNTING_FORM] [-v] [-vv]

.SH DESCRIPTION
hist2workspace is a utility to create RooFit/RooStats workspace from histograms

.SH OPTIONS
.IP -h\ --help
show this help message and exit
.IP -standard_form
default  model,  which  creates  an  extended PDF that interpolates between RooHistFuncs
.IP
This is much faster for models with many bins and uses significantly less memory
.IP -number_counting_form
This was the original model in 5.28 (without patches). It uses a Poisson for each
.IP
bin of the histogram.  This can become slow and memory intensive when there are many bins.
.IP

.IP -v
Switch HistFactory message stream to INFO level.
.IP -vv
Switch HistFactory message stream to DEBUG level.
